import { Open_Sans, Outfit } from "next/font/google";
import "./globals.css";
import UiProviders from "@/providers/UiProviders";
import "@flaticon/flaticon-uicons/css/all/all.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body className={`${openSans.variable} ${outfit.variable} antialiased`}>
        <UiProviders>{children}</UiProviders>
      </body>
    </html>
  );
}
